sudo: required
language: node_js
node_js:
- '8'
services:
- docker
- mongodb
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    tags: true
env:
  global:
  - secure: lVkQxqtv1w1tmgYn9XIYFF9yxyoKylhD6hYG69m5bJjRVDF2sgukK4mdZdoKEDbjjNi6F8mh4MZIQjD/O2c8R8KJhfobBT987uvIo0hrrry2hrAJtERkyXQGIVl119x7sPcKoCkSVnVMojQMictS3c/15LVtvA0Oix0OObsqxw8=
  - secure: Z13Ez11A8n7OewkgmvE4ku9/PL1ZwmHuQxhV2fjkxxF3jcCDABdbRRXyQuuWYNVoSfTT42OB/r5oUpHOd1NZigwJIfYZtdwUAHl77ZjbVK3aqkmczNvOjZxVI5dMpmPmNbNQvE65La5Hkq6gD2+IsOF4wXIJO2h62N2LIcfmkyY=
  - secure: Pz4lXdyit/t+PEt6EjpTtb0Wm16Wz9Oz3uFNTTeJJMM1S+nHZ45xatBp0xq6GI06S2E+BV80eU2fur4jnQEVrEiddLwJSL6kXoulw5jOcyonChTO2VMSoRO2+EUQM2rcTM4ZLdvHdVpp/f4YZ2m/nChJyBfT1kMfvnoOWCngXKQ=
