sudo: required
language: node_js
node_js:
- '8'
services:
- docker
- mongodb
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    tags: true
env:
  global:
  - secure: T8N+0b5fHIQr92VGsDojUK2GjkIL1Mw0LubrMXeagHHdX3JH24L/JOyquFijb/k9/sBGDqT9b7XeC1IeUHg6bAqWNkgbccP48q81I/tKf/9xQ9t8viy2SSFLQC0R/lAjfLlrebqAq2l14umfnhb4HZV7kqXKi3ASDwmUil8lmMU=
  - secure: hWe+qcpSiADUquVuL+K8SJAinKmmCRGr3xVMEpVnP79X37pRrSEirlIRGiEb7gcIwiAKMPCyaaNYSTtSJjCV64bCnTyknY8xUuLiUoqcWP2lzt4GZbtXlBKpXbHX6uVy044KvgAOhMFjjFDsT6n/IiI8J8klfwj/2kj4FxHckCY=
  - secure: hllvFk17s1ykkAwAm7Kw//sRWH0dOfksJJa3VCXGXW4SGbXbpe8wuRTXC+2yKO45azLr90R9nw95rsXUGY3i19eWaXcAVuU/j3sxsLjXdnVP0/nYC4nN30BxuGU/ATy7wdklSg2T38nY/9rq/u+gLZz8rqzdfTJ9wGX45WVpyZs=
